title: Blog
email: bendominguez011@gmail.com
description: >  # this means to ignore newlines until "baseurl:"
  This is just a simple blog where I write my thoughts.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bendominguez0111.github.io" # the base hostname & protocol for your site
